name: Publish package to the Maven Central Repository
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Build
        run: mvn -B package --file initial/pom.xml
      - name: check generated m2 settings
        run: |
          cat /home/runner/.m2/settings.xml
          export
      - name: Publish package
        run: mvn --batch-mode deploy --file initial/pom.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
